//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace couse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Count_of_students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Count_of_students()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int ID { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<bool> from_Minsk { get; set; }
        public Nullable<bool> from_the_countryside { get; set; }
        public Nullable<bool> from_other_regions { get; set; }
        public Nullable<bool> from_CIS_countries { get; set; }
        public Nullable<bool> from_other_countries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
