//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace couse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_about_student_families
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Information_about_student_families()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int id { get; set; }
        public Nullable<bool> single_parent_students { get; set; }
        public Nullable<bool> students_from_large_families { get; set; }
        public Nullable<bool> students_with_disabled_parents_1_2_groups { get; set; }
        public Nullable<bool> affected_by_the_Chernobyl_accident { get; set; }
        public Nullable<bool> disaster_victims { get; set; }
        public Nullable<bool> refugee_families { get; set; }
        public Nullable<bool> parents_died_during_passage_of_military_or_police_services { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
