//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace couse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsEntities2 : DbContext
    {
        public StudentsEntities2()
            : base("name=StudentsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorization> Autorization { get; set; }
        public virtual DbSet<Count_of_students> Count_of_students { get; set; }
        public virtual DbSet<Curators> Curators { get; set; }
        public virtual DbSet<Form_of_education> Form_of_education { get; set; }
        public virtual DbSet<Group_students> Group_students { get; set; }
        public virtual DbSet<Information_about_student_families> Information_about_student_families { get; set; }
        public virtual DbSet<Needing_social_protection> Needing_social_protection { get; set; }
        public virtual DbSet<Orphan_students> Orphan_students { get; set; }
        public virtual DbSet<Place_of_residence> Place_of_residence { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Students_id> Students_id { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
