//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace couse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Needing_social_protection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Needing_social_protection()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int ID { get; set; }
        public Nullable<int> orphan_students { get; set; }
        public Nullable<bool> lost_the_last_of_the_parents_in_the_period_of_study { get; set; }
        public Nullable<bool> in_custody { get; set; }
        public Nullable<bool> disabled_students { get; set; }
    
        public virtual Orphan_students Orphan_students1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
