//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace couse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_id
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> group_students { get; set; }
    
        public virtual Group_students Group_students1 { get; set; }
        public virtual Students Students { get; set; }
    }
}
